
services:
  postgres:
    image: postgres:16-alpine
    container_name: bitpacs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bitpacs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BitFix123Strong!
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    networks:
      - bitpacs-network
  backend-api:
    build:
      context: ./BitPacs/backend
      dockerfile: Dockerfile
    container_name: bitpacs-backend
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5151
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=bitpacs_db;User Id=postgres;Password=BitFix123Strong!;
      - JwtSettings__Issuer=bitpacs-api
      - JwtSettings__SecretKey=BitPacs-Super-Secret-Key-2024-Secure-Token-Generation-Key
      - JwtSettings__Audience=bitpacs-front
    ports:
      - "0.0.0.0:5151:5151"
    depends_on:
      - postgres
    networks:
      - bitpacs-network
    volumes:
      - ./logs/backend:/app/logs
    command: >
      sh -c "sleep 15 && dotnet BitPacs.Api.dll"
  frontend:
    build:
      context: ./BitPacs/frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://10.31.0.232:5151
    container_name: bitpacs-frontend
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:80"
    depends_on:
      - backend-api
    networks:
      - bitpacs-network

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/bitpacs-data/postgres

networks:
  bitpacs-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
